# aggiornamento incrementale
#incremental: true
# aggiunta per prova 31/01/21
#permalink: /:slug/
breadcrumbs: true # disabled by default
kramdown:
  auto_ids: true

sass:
  sass_dir: assets/scss/
  style: compressed
  # Exclude from processing.
  exclude:
    - bower_components
#finale
# Site settings
# SEO START
vers: "1.0.36"
title: "" # BACKEND
tagline: "" # BACKEND
email: "" # BACKEND
description: "" # BACKEND
keywords: "" # BACKEND
baseurl: "" 
# Google Search Console
google_site_verification: ""
# Google Analytics Console
google_analytics: "G-6JWK8SGVLM"
locale: es #- The locale these tags are marked up in. Of the format # BACKEND


toc:
  min_level: 1
  max_level: 6
  no_toc_section_class: no_toc_section
  list_class: section-nav
  sublist_class: ""
  item_class: toc-entry
  item_prefix: toc-


## TIMEZONE
timezone: Europe/Rome # ATTENTO PERMETTERE IL CAMBIAMENTO IN PRODUZIONE

# Build settings
markdown: kramdown
theme: minima
url: "https://ayuda.proyectochasqui.com" # the base hostname & protocol for your site # BACKEND
production: true
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-archives
  - jekyll-toc
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-get-json
  - jekyll-datapage-generator

# JEKYLL-ARCHIVES FINE
autopages:
  enabled: false #DISABILITA LA CREAZIONE AUTOMATICA DELLE PAGINE TAG, CATEGORY ..

# Tag Options

permalink: /:title/
feed:
  collections:
    posts:
      path: "/index.xml"

jekyll_get_json:
  - data: header
    json: "https://tiledesk-cms-server-prod.herokuapp.com/63b47fbd017c8a001a3cdad7/63b4821a2a77a80023e20df9/settings"
  # - data: autori
  #   json: 'https://tiledesk-cms-server-prod.herokuapp.com/63b47fbd017c8a001a3cdad7/63b4821a2a77a80023e20df9/users'
  - data: categories
    json: "https://tiledesk-cms-server-prod.herokuapp.com/63b47fbd017c8a001a3cdad7/63b4821a2a77a80023e20df9/collections"
  - data: articles
    json: "https://tiledesk-cms-server-prod.herokuapp.com/63b47fbd017c8a001a3cdad7/63b4821a2a77a80023e20df9/contents?format=full"


page_gen-dirs: true

page_gen:
  - data: 'categories'
    template: 'categorias-interna'
    dir: 'categorias'
    name: 'slug'
  - data: 'articles'
    template: 'blog'
    dir: 'articulos'
    name: 'slug'